### ISSUE TITLE
Not building correctly. 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Bergeypvp#2]
2015-04-14 23:19:53 [ERROR] Could not load 'plugins/BergeyPvP-0.1-3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/valadian/bergecraft/ABergMod
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.NoClassDefFoundError: com/valadian/bergecraft/ABergMod
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_75]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_75]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_75]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_75]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_75]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_75]
        at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.valadian.bergecraft.ABergMod
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_75]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_75]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]                                                                                        [130/9509]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_75]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_75]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_75]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_75]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_75]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_75]
        at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 6 more

**Comment by rourke750** [comment]
Did you add the merge mod on civtest?

**Comment by ttk2** [comment]
merge mod?

**Comment by rourke750** [comment]
Berge Core mod plugin thing?

**Comment by ttk2** [comment]
I need to be running that too?

**Comment by WildWeazel** [comment]
yes #1

**Comment by ttk2** [comment]
put that on, getting a new stack now .

2015-04-16 00:41:30 [INFO] [BergeyPvp] Loading BergeyPvp v0.1
2015-04-16 00:41:30 [ERROR]
com/gimmicknetwork/gimmickapi/PlayerLeavePvpModeEvent initializing
BergeyPvp v0.1 (Is it up to date?)
java.lang.NoClassDefFoundError:
com/gimmicknetwork/gimmickapi/PlayerLeavePvpModeEvent
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.7.0_75]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
~[?:1.7.0_75]
        at java.lang.Class.privateGetPublicMethods(Class.java:2733)
~[?:1.7.0_75]
        at java.lang.Class.getMethods(Class.java:1472) ~[?:1.7.0_75]
        at com.valadian.bergecraft.Config.scanAnnotations(Config.java:71)
~[?:?]
        at com.valadian.bergecraft.Config.<init>(Config.java:54) ~[?:?]
        at
com.valadian.bergecraft.ABergMod.loadConfiguration(ABergMod.java:102) ~[?:?]
        at com.valadian.bergecraft.ABergMod.onLoad(ABergMod.java:97) ~[?:?]
        at
org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:374)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.ClassNotFoundException:
com.gimmicknetwork.gimmickapi.PlayerLeavePvpModeEvent
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
~[?:1.7.0_75]
        at java.security.AccessController.doPrivileged(Native Method)
~[?:1.7.0_75]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
~[?:1.7.0_75]
        at
org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
~[?:1.7.0_75]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
~[?:1.7.0_75]
        ... 12 more

**Comment by rourke750** [comment]
Did you add the gimmickapi?

**Comment by ttk2** [comment]
I need that too?

**Comment by rourke750** [comment]
Yep. That's how dependencies work :P. I  might be able to remove them.

**Comment by WildWeazel** [comment]
We can remove it but then it makes it harder to drop a new version onto CivPVP

**Comment by ttk2** [comment]
that's not my concern, my concern is that it should just note what plugin
is missing.

**Comment by rourke750** [comment]
It does.
