### ISSUE TITLE
Could not load 'plugins/bergmodcore.jar'

### ISSUE THREAD

**Issue by ghost** [Civcraft/Bergeypvp#7]
2015-06-23 13:49:57 [ERROR] Could not load 'plugins/bergmodcore.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:291) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at vg.civcraft.mc.civmodcore.ACivMod.<init>(ACivMod.java:18) ~[?:?]
        at Dummy.<init>(Dummy.java:3) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_45-internal]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_45-internal]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_45-internal]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_45-internal]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        ... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:125) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at vg.civcraft.mc.civmodcore.ACivMod.<init>(ACivMod.java:18) ~[?:?]
        at Dummy.<init>(Dummy.java:3) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_45-internal]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_45-internal]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_45-internal]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_45-internal]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        ... 6 more

**Comment by rourke750** [comment]
Just remove it.
